# Generated by Django 3.1.6 on 2021-03-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_friends'),
        ('posts', '0006_auto_20210315_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes', to='profiles.Profile'),
        ),
    ]
