# Generated by Django 3.1.6 on 2021-03-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210316_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='commentText',
        ),
    ]
