# Generated by Django 3.1.6 on 2021-03-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210316_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentText',
            new_name='comment',
        ),
    ]
